// <auto-generated />
using System;
using BayMarch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BayMarch.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210412143655_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BayMarch.Models.Price", b =>
                {
                    b.Property<long>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrantBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrantComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GrantFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantToDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ItemPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("PriceNum")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("SysComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PriceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Price");
                });

            modelBuilder.Entity("BayMarch.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long>("GlobalBarCode")
                        .HasColumnType("bigint");

                    b.Property<string>("GrantBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrantComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GrantFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantToDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ItemNum")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalBarCode")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceID")
                        .HasColumnType("bigint");

                    b.Property<string>("SysComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TaxId")
                        .HasColumnType("bigint");

                    b.Property<float>("TaxValue")
                        .HasColumnType("real");

                    b.Property<bool>("Taxed")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BayMarch.Models.Seller", b =>
                {
                    b.Property<long>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("GrantBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrantComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GrantFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantToDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SellerNum")
                        .HasColumnType("bigint");

                    b.Property<string>("SysComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SellerId");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("BayMarch.Models.Price", b =>
                {
                    b.HasOne("BayMarch.Models.Product", "ProductObj")
                        .WithMany("ItemPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BayMarch.Models.Seller", "SellerObj")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductObj");

                    b.Navigation("SellerObj");
                });

            modelBuilder.Entity("BayMarch.Models.Product", b =>
                {
                    b.Navigation("ItemPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
